// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANDXeEkGLiUcDVlLejCMrbwcRl6Fw0kiI',
    appId: '1:468149753273:web:ca92475f59b0adc4d61268',
    messagingSenderId: '468149753273',
    projectId: 'flutter-7f535',
    authDomain: 'flutter-7f535.firebaseapp.com',
    storageBucket: 'flutter-7f535.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhxbNl8M0TSMHIFws2g9PkAwdRjbgmirI',
    appId: '1:468149753273:android:542da4ea752430e4d61268',
    messagingSenderId: '468149753273',
    projectId: 'flutter-7f535',
    storageBucket: 'flutter-7f535.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeLMVrMMAakma8EyEEOvP8fWC86DMSFCQ',
    appId: '1:468149753273:ios:b27ffc6384cdc255d61268',
    messagingSenderId: '468149753273',
    projectId: 'flutter-7f535',
    storageBucket: 'flutter-7f535.appspot.com',
    iosClientId:
        '468149753273-s29khv4j8nbarggrtdg4paipj215rop9.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeLMVrMMAakma8EyEEOvP8fWC86DMSFCQ',
    appId: '1:468149753273:ios:b27ffc6384cdc255d61268',
    messagingSenderId: '468149753273',
    projectId: 'flutter-7f535',
    storageBucket: 'flutter-7f535.appspot.com',
    iosClientId:
        '468149753273-s29khv4j8nbarggrtdg4paipj215rop9.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoAppFirebase',
  );
}
